package easy

/**
 * You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */

fun findTheDifference(s: String, t: String): Char {
    val mapS = HashMap<Char,Int>()
    val mapT = HashMap<Char,Int>()

    s.forEach { char->
        mapS[char]= (mapS[char]?:0)+1
    }

    t.forEach { char->
        mapT[char]= (mapT[char]?:0)+1
    }

    var diff=' '

    for ( entry in mapT.entries)
    {
        val count = mapS[entry.key]?:0
        if(count<entry.value )
        {
            diff=entry.key
            break
        }

    }
return  diff
}